version: "3"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    container_name: chirpstack-networkserver
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices:/opt/lorawan-devices
    environment:
      - MQTT_BROKER_HOST=e7nrx1.stackhero-network.com
      - MQTT_BROKER_PORT=13584
      - MQTT_BROKER_USERNAME=admin
      - MQTT_BROKER_PASSWORD=fDbGcjMPR9vokqeoOx5UWHCHrnuGh3fQ
      - REDIS_HOST=private-bahamut-do-user-4923456-0.i.db.ondigitalocean.com:25061
    ports:
      - 8080:8080

#   chirpstack-gateway-bridge-in865:
#     image: chirpstack/chirpstack-gateway-bridge:4
#     restart: unless-stopped
#     container_name: chirpstack-gateway-bridge-in865-semtech
#     ports:
#       - 1700:1700/udp
#       - 3001:3001
#     volumes:
#       - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
# #      - ./configuration/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-in865.toml:/etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
#     environment:
#       - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=in865/gateway/{{ .GatewayID }}/event/{{ .EventType }}
#       - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=in865/gateway/{{ .GatewayID }}/state/{{ .StateType }}
#       - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=in865/gateway/{{ .GatewayID }}/command/#
#       #- CHIRPSTACK_NETWORK_SERVER__NETWORK__EXTRA_CHANNELS__0__FREQUENCY=865375000
#       #- CHIRPSTACK_NETWORK_SERVER__NETWORK__EXTRA_CHANNELS__0__MIN_DR=0
#       #- CHIRPSTACK_NETWORK_SERVER__NETWORK__EXTRA_CHANNELS__0__MAX_DR=5
#       #- CHIRPSTACK_NETWORK_SERVER__NETWORK__EXTRA_CHANNELS__1__FREQUENCY=865687500
#       #- CHIRPSTACK_NETWORK_SERVER__NETWORK__EXTRA_CHANNELS__1__MIN_DR=0
#       #- CHIRPSTACK_NETWORK_SERVER__NETWORK__EXTRA_CHANNELS__1__MAX_DR=5

#   chirpstack-gateway-bridge-eu868:
#     image: chirpstack/chirpstack-gateway-bridge:4
#     restart: unless-stopped
#     container_name: chirpstack-gateway-bridge-eu868-semtech
#     ports:
#       - 1701:1700/udp
#       - 3002:3002
#     volumes:
#       - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
# #      - ./configuration/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml:/etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
#     environment:
#       - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
#       - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
#       - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#